### ISSUE TITLE
Show View over Modals(Sheets)

### ISSUE THREAD

**Issue by halilyuce** [tamasdancsi/ios-full-screen-modal#1]
Hello, thanks for this repo firstly :)

Is it possible to show modal over sheets or all other views? I want to show an image viewer everywhere. For example, if I opened a user profile sheet, I want to show the image viewer over that but the overlay is not working well. It stays behind the sheet.

**Comment by tamasdancsi** [comment]
Hey @halilyuce :) Unfortunately I don't think you can do that. At the end of the day your modal is basically hacked into a `ZStack` (https://github.com/tamasdancsi/ios-full-screen-modal/blob/main/Sources/FullScreenModal/FullScreenModalWrapper.swift), therefore all native sheets or actual modals will cover it.
